name: Renovate check

on:
  pull_request:
    paths:
      - renovate.json

jobs:
  renovate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install renovate
        run: npm install --global re2 renovate
      - name: Check renovate config
        run: renovate-config-validator renovate.json
      - name: Renovate dry-run
        run: renovate --dry-run=full --autodiscover --print-config
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
